import openpyxl
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, Border, Side, PatternFill
from openpyxl.utils import get_column_letter

wb = Workbook()
ws = wb.active
ws.title = "Substation Workflows"

# ── Headers ──────────────────────────────────────────────────────────────────
headers = [
    "Workflow No.",
    "Workflow Name",
    "Sub-Module / Step",
    "Description",
    "Source URL 1",
    "Source URL 2",
    "Source URL 3",
    "Covered in Document (PDF)"
]

# ── Full Data ─────────────────────────────────────────────────────────────────
# Format: (wf_no, wf_name, sub_module, description, url1, url2, url3, docs)
data = [

    # ─── WORKFLOW 1 ───────────────────────────────────────────────────────────
    ("1","Bid Process in Substation EPC Projects",
     "Tender / NIT Received – Opportunity Identification",
     "Company receives Tender or Notice Inviting Tender from client containing project requirements, specs, scope, timelines and eligibility criteria.",
     "https://constructionfront.com/epc-contract/",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://www.sora.ro/2026/05/31/epc-versus-fidic-contracts/",
     "Substation.docx; WBSETCL General Technical Specification (Turnkey); OEU White Substation RFP Exhibit A"),

    ("1","Bid Process in Substation EPC Projects",
     "Bid / No-Bid Decision – Opportunity Evaluation",
     "Management evaluates project opportunity against company capacity, financials, technical capability and strategic fit before deciding to bid.",
     "https://www.procore.com/library/epc-contractors",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://prismecs.com/blog/understanding-the-lifecycle-of-epc-solutions-services",
     "Substation.docx; OEU White Substation RFP Exhibit A"),

    ("1","Bid Process in Substation EPC Projects",
     "Eligibility & Pre-Bid – Qualification Verification",
     "Contractor verifies eligibility criteria, attends pre-bid meetings, submits queries, and confirms technical and financial qualifications.",
     "https://www.euci.com/event_post/epc-contracts/",
     "https://fidic.org/sites/default/files/The%20FIDIC%20Contracts%20Guide.pdf",
     "https://dancumberlandlabs.com/blog/epc-engineering-procurement-construction/",
     "Substation.docx; OEU White Substation RFP Exhibit A (Pre-Bid Meeting Section)"),

    ("1","Bid Process in Substation EPC Projects",
     "Scope Review & Quantity Take-Off – Understanding Project Scope",
     "Engineering team reviews tender drawings and documents, performs quantity take-off for all civil, electrical and mechanical works.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://electrical-engineering-portal.com/turnkey-substation-technical-documentation",
     "Substation.docx; WBSETCL General Technical Specification (Turnkey); OEU White Substation RFP Exhibit A"),

    ("1","Bid Process in Substation EPC Projects",
     "Vendor & Subcontractor Quotations – Market Cost Collection",
     "Procurement team collects quotations from vendors, subcontractors and suppliers for all equipment, materials and services required.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://electrical-engineering-portal.com/checks-for-successful-substation-factory-acceptance-testing",
     "https://www.euci.com/event_post/epc-contracts-remote/",
     "Substation.docx; WBSETCL General Technical Specification (Turnkey)"),

    ("1","Bid Process in Substation EPC Projects",
     "Parallel Cost Estimation – Detailed Cost Calculation",
     "Estimating team calculates detailed project costs including civil, electrical, mechanical, manpower, overheads and logistics.",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://prismecs.com/blog/understanding-the-lifecycle-of-epc-solutions-services",
     "https://constructionfront.com/epc-contract/",
     "Substation.docx"),

    ("1","Bid Process in Substation EPC Projects",
     "Base Cost Estimation – Total Project Cost Consolidation",
     "All cost elements are consolidated into a single base cost estimate representing total project execution cost.",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://www.pmi.org/learning/library/realizing-engineering-procurement-construction-projects-7173",
     "https://constructionfront.com/epc-contract/",
     "Substation.docx; OEU White Substation RFP Exhibit A (Budget: $3.8M)"),

    ("1","Bid Process in Substation EPC Projects",
     "Risk & Contingency Analysis – Project Risk Assessment",
     "Risk team identifies project risks, quantifies impact, and adds contingency provisions to the cost estimate.",
     "https://www.mayerbrown.com/Files/Publication/35328234-d6f9-49c7-bbe8-964945bb9158/Presentation/PublicationAttachment/96527455-174f-4e1a-9a9c-9a1d66e9bde3/EPC_contracts_jan15_hosie.pdf",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://www.pmi.org/learning/library/realizing-engineering-procurement-construction-projects-7173",
     "Substation.docx"),

    ("1","Bid Process in Substation EPC Projects",
     "Margin Finalization – Profit Strategy Definition",
     "Management finalizes profit margin, commercial strategy and overall bid price based on market conditions and competition.",
     "https://www.euci.com/event_post/epc-contracts/",
     "https://www.pillsburylaw.com/a/web/157254/EPC-Agreement-Provisions.pdf",
     "https://prismecs.com/blog/understanding-the-lifecycle-of-epc-solutions-services",
     "Substation.docx"),

    ("1","Bid Process in Substation EPC Projects",
     "Technical & Commercial Bid Preparation – Proposal Creation",
     "Bid team prepares complete technical proposal and commercial offer documents as per tender requirements for submission.",
     "https://www.pillsburylaw.com/a/web/157254/EPC-Agreement-Provisions.pdf",
     "https://fidic.org/sites/default/files/The%20FIDIC%20Contracts%20Guide.pdf",
     "https://www.euci.com/event_post/epc-contracts/",
     "Substation.docx; OEU White Substation RFP Exhibit A; WBSETCL General Technical Specification (Turnkey)"),

    ("1","Bid Process in Substation EPC Projects",
     "Client Evaluation – Tender Assessment by Client",
     "Client evaluates all received bids for technical compliance, commercial competitiveness and contractor qualifications.",
     "https://www.procore.com/library/epc-contractors",
     "https://www.sora.ro/2026/05/31/epc-versus-fidic-contracts/",
     "https://constructionfront.com/epc-contract/",
     "Substation.docx; OEU White Substation RFP Exhibit A"),

    ("1","Bid Process in Substation EPC Projects",
     "Bid Award (LOA) – Project Successfully Won",
     "Client issues Letter of Award (LOA) confirming contractor selection. This officially awards the project to the winning bidder.",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "https://pmri.in/epccompletion/",
     "https://www.pillsburylaw.com/a/web/157254/EPC-Agreement-Provisions.pdf",
     "Substation.docx; OEU White Substation RFP Exhibit A; WBSETCL General Technical Specification (Turnkey)"),

    ("1","Bid Process in Substation EPC Projects",
     "Contract Finalization & PBG – Legal Agreement Completion",
     "Contract terms are agreed and signed. Contractor submits Performance Bank Guarantee (PBG) as required by contract.",
     "https://fidic.org/sites/default/files/The%20FIDIC%20Contracts%20Guide.pdf",
     "https://lauwtjunnji.weebly.com/uploads/1/0/1/7/10171621/fidic_-_conditions_of_contract_for_epc_(turnkey)_projects_(1999).pdf",
     "https://www.pillsburylaw.com/a/web/157254/EPC-Agreement-Provisions.pdf",
     "Substation.docx; OEU White Substation RFP Exhibit A"),

    # ─── WORKFLOW 2 ───────────────────────────────────────────────────────────
    ("2","Contract Finalization and Project Mobilization Process",
     "LOA / LOI Received – Project Award Confirmation",
     "Organization receives Letter of Award (LOA) or Letter of Intent (LOI) from client officially confirming project award.",
     "https://pmri.in/epccompletion/",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "https://www.sora.ro/2026/05/31/epc-versus-fidic-contracts/",
     "Substation.docx; OEU White Substation RFP Exhibit A"),

    ("2","Contract Finalization and Project Mobilization Process",
     "Draft and Review Contract – Contract Preparation",
     "Legal and commercial teams draft the contract document covering scope, price, schedule, penalties, warranties and special conditions.",
     "https://fidic.org/sites/default/files/The%20FIDIC%20Contracts%20Guide.pdf",
     "https://lauwtjunnji.weebly.com/uploads/1/0/1/7/10171621/fidic_-_conditions_of_contract_for_epc_(turnkey)_projects_(1999).pdf",
     "https://www.pillsburylaw.com/a/web/157254/EPC-Agreement-Provisions.pdf",
     "Substation.docx; OEU White Substation RFP Exhibit A (Deliverables Section)"),

    ("2","Contract Finalization and Project Mobilization Process",
     "Negotiation and Finalization – Commercial and Legal Alignment",
     "Both parties negotiate commercial terms, technical clarifications, payment schedules and risk allocation before signing.",
     "https://petroedgeasia.net/training/engineering-procurement-construction-contracts-epc-training-course/",
     "https://fidic.org/sites/default/files/The%20FIDIC%20Contracts%20Guide.pdf",
     "https://www.euci.com/event_post/epc-contracts/",
     "Substation.docx"),

    ("2","Contract Finalization and Project Mobilization Process",
     "Contract Signing – Legal Agreement Execution",
     "Authorized representatives from both parties sign the final contract document making it legally binding and effective.",
     "https://fidic.org/sites/default/files/The%20FIDIC%20Contracts%20Guide.pdf",
     "https://www.pillsburylaw.com/a/web/157254/EPC-Agreement-Provisions.pdf",
     "https://constructionfront.com/epc-contract/",
     "Substation.docx; OEU White Substation RFP Exhibit A"),

    ("2","Contract Finalization and Project Mobilization Process",
     "Parallel Compliance Activities – Financial and Regulatory Commitments",
     "Contractor arranges advance bank guarantee (ABG), insurance policies, regulatory registrations and statutory compliance.",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://lauwtjunnji.weebly.com/uploads/1/0/1/7/10171621/fidic_-_conditions_of_contract_for_epc_(turnkey)_projects_(1999).pdf",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "Substation.docx; WBSETCL General Technical Specification (Turnkey)"),

    ("2","Contract Finalization and Project Mobilization Process",
     "Contract Effective – Contract Activation",
     "Contract becomes officially effective (Effective Date). Project clock starts. All teams are notified and project systems activated.",
     "https://pmri.in/epccompletion/",
     "https://fidic.org/sites/default/files/The%20FIDIC%20Contracts%20Guide.pdf",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "Substation.docx"),

    ("2","Contract Finalization and Project Mobilization Process",
     "Bid to Execution Handover – Ownership Transfer",
     "Bid team formally hands over all project documentation, commitments and technical details to the execution project management team.",
     "https://projectmanagement123.com/project-completion-and-handover-procedure/",
     "https://pmri.in/epccompletion/",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "Substation.docx"),

    ("2","Contract Finalization and Project Mobilization Process",
     "Project Planning Activities – Execution Preparation",
     "Project Manager prepares detailed execution plan, work breakdown structure (WBS), resource plan, procurement schedule and baseline programme.",
     "https://www.pmi.org/learning/library/realizing-engineering-procurement-construction-projects-7173",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://prismecs.com/blog/understanding-the-lifecycle-of-epc-solutions-services",
     "Substation.docx; WBSETCL General Technical Specification – L2 Networks Section"),

    # ─── WORKFLOW 3 ───────────────────────────────────────────────────────────
    ("3","Project Mobilization and Site Establishment Process",
     "Mobilization Advance and Bank Guarantee",
     "Contractor processes mobilization advance payment received from client and submits required Bank Guarantee (BG) as financial security.",
     "https://lauwtjunnji.weebly.com/uploads/1/0/1/7/10171621/fidic_-_conditions_of_contract_for_epc_(turnkey)_projects_(1999).pdf",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "https://pmri.in/epccompletion/",
     "Substation.docx; WBSETCL General Technical Specification (Turnkey)"),

    ("3","Project Mobilization and Site Establishment Process",
     "Site Possession – Physical Site Handover",
     "Client formally hands over physical site to contractor. Contractor takes possession and begins site establishment activities.",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "Substation.docx; Eskom Dinaledi Civil SOW (DIN20P07-SE-E82); Valard – 10 Stages of Substation Construction"),

    ("3","Project Mobilization and Site Establishment Process",
     "Resource Mobilization – Manpower and Equipment Deployment",
     "Project team, skilled manpower, construction equipment, site office infrastructure and temporary facilities are mobilized to site.",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://prismecs.com/blog/understanding-the-lifecycle-of-epc-solutions-services",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "Substation.docx; Valard – 10 Stages (Brushing & Site Clearing)"),

    ("3","Project Mobilization and Site Establishment Process",
     "Temporary Infrastructure Setup",
     "Site office, labor camp, water supply, electricity connection, stores, laydown area, roads and fencing established for project operation.",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx; Eskom Dinaledi Civil SOW; OEU White Substation RFP (Site Housekeeping Section)"),

    ("3","Project Mobilization and Site Establishment Process",
     "Health, Safety and Environment (HSE) Setup",
     "Site safety plan, emergency response procedures, HSE documentation and safety inductions established before any work begins.",
     "https://electra.cigre.org/311-august-2020/technical-brochures/guidelines-for-safe-work-methods-in-substations.html",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "Eskom Dinaledi Civil SOW (OHS Act Reference); OEU White Substation RFP (Working Hours & Housekeeping)"),

    ("3","Project Mobilization and Site Establishment Process",
     "Site Established – Ready for Execution",
     "Milestone confirming site is physically operational and all prerequisites for active work execution are in place.",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://prismecs.com/blog/understanding-the-lifecycle-of-epc-solutions-services",
     "Substation.docx; Valard – 10 Stages of Substation Construction"),

    # ─── WORKFLOW 4 ───────────────────────────────────────────────────────────
    ("4","Survey, Geotechnical Investigation and Design Release Process",
     "Benchmark Points and Grid Layout",
     "Survey crews establish fixed benchmark reference points and GPS-based grid layout across the project site for measurement accuracy.",
     "https://906a6d36-valard.com",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "Substation.docx; Valard – 10 Stages (Survey & Geotechnical Studies); OEU White Substation RFP (Site Survey Item)"),

    ("4","Survey, Geotechnical Investigation and Design Release Process",
     "Topographic Survey",
     "Survey team conducts detailed topographic survey of the site capturing elevation, contours, existing structures and boundaries.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "Substation.docx; OEU White Substation RFP (Site Survey / Utility Locates)"),

    ("4","Survey, Geotechnical Investigation and Design Release Process",
     "Soil Investigation / Geotechnical Testing",
     "Geotechnical team performs bore holes, soil sampling and laboratory tests to determine soil bearing capacity, permeability and properties.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "Substation.docx; Valard – 10 Stages (Survey & Geotechnical Studies); OEU White Substation RFP (Geotechnical Report)"),

    ("4","Survey, Geotechnical Investigation and Design Release Process",
     "Geotechnical Report Preparation",
     "Engineering team prepares geotechnical investigation report with soil test results, bearing capacity, recommendations for foundation design.",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "Substation.docx; OEU White Substation RFP (Geotechnical Report – Contractor Responsibility Item 9)"),

    ("4","Survey, Geotechnical Investigation and Design Release Process",
     "Technical Review and Client Approval",
     "Draft geotechnical and survey reports submitted for internal review and client approval. Comments incorporated and final report issued.",
     "https://electrical-engineering-portal.com/turnkey-substation-technical-documentation",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://www.pmi.org/learning/library/realizing-engineering-procurement-construction-projects-7173",
     "Substation.docx; WBSETCL General Technical Specification (Drawing Approval Process)"),

    ("4","Survey, Geotechnical Investigation and Design Release Process",
     "Design Basis Finalized – Inputs for Engineering Released",
     "All survey and geotechnical data formally released as engineering inputs. Design basis document finalized for use by engineering teams.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://electrical-engineering-portal.com/turnkey-substation-technical-documentation",
     "Substation.docx; WBSETCL General Technical Specification (Technical Particulars of System)"),

    # ─── WORKFLOW 5 ───────────────────────────────────────────────────────────
    ("5","Detailed Engineering and IFC Release Process",
     "Design Basis and Engineering Inputs Collection",
     "Engineers collect all technical requirements: tender specs, client needs, geotech reports, electrical loads, site survey data and grid requirements.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://www.academia.edu/93132452/ElECTRIC_POWER_SUBSTATIONS_ENGINEERING",
     "Substation.docx; WBSETCL General Technical Specification (Turnkey); OEU RFP – 30% Design Items"),

    ("5","Detailed Engineering and IFC Release Process",
     "Single Line Diagram (SLD) Preparation",
     "Electrical engineers develop switching SLD and metering/relaying SLD showing all equipment, connections and protection schemes.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://www.academia.edu/93132452/ElECTRIC_POWER_SUBSTATIONS_ENGINEERING",
     "https://keentelengineering.com/ieee-compliant-ehv-hv-mv-substation-design-services-by-keentel-engineering",
     "Substation.docx; WBSETCL General Technical Specification; OEU RFP – SLD Deliverable at 30%"),

    ("5","Detailed Engineering and IFC Release Process",
     "General Arrangement and Layout Design",
     "Equipment layout, switchyard arrangement, control room position and general arrangement plans developed based on approved SLD.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://www.academia.edu/93132452/ElECTRIC_POWER_SUBSTATIONS_ENGINEERING",
     "Substation.docx; WBSETCL General Technical Specification (Land Utilisation Plan); OEU RFP – General Arrangement Plan"),

    ("5","Detailed Engineering and IFC Release Process",
     "Civil and Structural Design",
     "Civil engineers design foundations, grading, drainage, cable trenches, structural steel supports, earthmat and control room building.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://www.academia.edu/93132452/ElECTRIC_POWER_SUBSTATIONS_ENGINEERING",
     "Substation.docx; Eskom Dinaledi Civil SOW; OEU RFP – Civil Design at 60%; WBSETCL (Foundation Design)"),

    ("5","Detailed Engineering and IFC Release Process",
     "Protection, Control and SCADA Design",
     "Protection engineers design relay schemes, control panel layouts, AC/DC schematics, SCADA integration and communication block diagrams.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://seclab.illinois.edu/wp-content/uploads/2011/03/iec61850-intro.pdf",
     "https://library.e.abb.com/public/5ea2620c3dec4376a1540fc2b07a18b7/IEC%2061850%20Overview_Self.pdf",
     "Substation.docx; WBSETCL General Technical Specification (Control & Protection Schemes); OEU RFP – Relay/Control Panel Specs"),

    ("5","Detailed Engineering and IFC Release Process",
     "Grounding and Earthing Design",
     "Earth mat layout, ground grid design, lightning protection design and earthing calculations prepared per IEEE Std. 80.",
     "https://keentelengineering.com/ieee-compliant-ehv-hv-mv-substation-design-services-by-keentel-engineering",
     "https://www.academia.edu/93132452/ElECTRIC_POWER_SUBSTATIONS_ENGINEERING",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "Substation.docx; WBSETCL General Technical Specification (Earth Mat Layout); OEU RFP – IEEE Std 80 Reference; Eskom Dinaledi SOW (Earthing Standard Ref)"),

    ("5","Detailed Engineering and IFC Release Process",
     "Cable and Raceway Design",
     "Underground raceway plans, conduit schedules, cable pulling schedules and cable trench layouts designed for all power and control cables.",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "https://keentelengineering.com/ieee-compliant-ehv-hv-mv-substation-design-services-by-keentel-engineering",
     "https://www.academia.edu/93132452/ElECTRIC_POWER_SUBSTATIONS_ENGINEERING",
     "Substation.docx; OEU RFP – Underground Raceway Plan at 60%; WBSETCL (Cable Supply Scope)"),

    ("5","Detailed Engineering and IFC Release Process",
     "Engineering Calculations (Fault, Battery, Lightning, Grounding)",
     "Engineering team performs fault current analysis, battery sizing, lightning protection and grounding calculations to validate design.",
     "https://keentelengineering.com/ieee-compliant-ehv-hv-mv-substation-design-services-by-keentel-engineering",
     "https://www.academia.edu/93132452/ElECTRIC_POWER_SUBSTATIONS_ENGINEERING",
     "https://electrical-engineering-portal.com/power-substation-design-engineering",
     "Substation.docx; OEU White Substation RFP (Calculations at 60% – Fault, Battery, Lightning)"),

    # ─── WORKFLOW 6 ───────────────────────────────────────────────────────────
    ("6","Submit for Approval – Client Submission Process",
     "Drawing and Document Submission to Client",
     "All engineering drawings, calculations and specifications submitted to client for review in sequential order as per approval schedule.",
     "https://electrical-engineering-portal.com/turnkey-substation-technical-documentation",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://www.academia.edu/93132452/ElECTRIC_POWER_SUBSTATIONS_ENGINEERING",
     "Substation.docx; WBSETCL General Technical Specification (Drawings to be Furnished Section); OEU RFP – 30/60/90% Review Gates"),

    ("6","Submit for Approval – Client Submission Process",
     "Client Technical Review and Comments",
     "Client engineering team reviews submitted documents for technical compliance, design methodology, safety standards and project requirements.",
     "https://electrical-engineering-portal.com/turnkey-substation-technical-documentation",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://www.pmi.org/learning/library/realizing-engineering-procurement-construction-projects-7173",
     "Substation.docx; OEU RFP – 30/60/90% Review Process; WBSETCL (Modification by WBSETCL Section)"),

    ("6","Submit for Approval – Client Submission Process",
     "Revision Incorporation and Resubmission",
     "Contractor incorporates client comments into drawings, updates calculations and resubmits revised documents for final approval.",
     "https://electrical-engineering-portal.com/turnkey-substation-technical-documentation",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "Substation.docx; WBSETCL (Any modification shall be incorporated and resubmitted)"),

    ("6","Submit for Approval – Client Submission Process",
     "Approved – IFC (Issued for Construction) Release",
     "Client grants final approval. Drawings are stamped IFC (Issued for Construction) and released to construction and procurement teams.",
     "https://electrical-engineering-portal.com/turnkey-substation-technical-documentation",
     "https://keentelengineering.com/a-guide-to-the-substation-design-process",
     "https://www.academia.edu/93132452/ElECTRIC_POWER_SUBSTATIONS_ENGINEERING",
     "Substation.docx; OEU RFP – Record Drawing Section; WBSETCL (Approval Clause)"),

    # ─── WORKFLOW 7 ───────────────────────────────────────────────────────────
    ("7","Procurement, Vendor Approval and Manufacturing Process",
     "Procurement Plan Preparation",
     "Procurement team identifies all materials and equipment required, prioritizes long-lead items, defines vendor strategy and aligns with project schedule.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://www.procore.com/library/epc-contractors",
     "Substation.docx; OEU RFP – Procurement Specifications Section; WBSETCL (Supply and Delivery Scope Items)"),

    ("7","Procurement, Vendor Approval and Manufacturing Process",
     "Request for Quotation (RFQ) and Vendor Identification",
     "RFQs issued to approved vendors for all equipment. Technical specifications and commercial terms shared with potential suppliers.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://electrical-engineering-portal.com/checks-for-successful-substation-factory-acceptance-testing",
     "https://www.euci.com/event_post/epc-contracts-remote/",
     "Substation.docx; WBSETCL (Makers List of Equipment); OEU RFP (OEU will provide Transformers & Breakers)"),

    ("7","Procurement, Vendor Approval and Manufacturing Process",
     "Bid Evaluation and Techno-Commercial Comparison",
     "Procurement team evaluates vendor quotations technically and commercially, prepares comparative statements and recommends preferred vendor.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://www.euci.com/event_post/epc-contracts/",
     "Substation.docx; WBSETCL General Technical Specification (Workmanship – Bid Conformity Section)"),

    ("7","Procurement, Vendor Approval and Manufacturing Process",
     "Purchase Order (PO) Issuance and Vendor Approval",
     "Purchase Order issued to selected vendors. Vendor drawings and technical submittals reviewed and approved before manufacturing begins.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://electrical-engineering-portal.com/checks-for-successful-substation-factory-acceptance-testing",
     "https://keentelengineering.com/substation-testing-lifecycle-fat-vs-sat",
     "Substation.docx; WBSETCL (Equipment Drawings for Approval Section); OEU RFP – Procurement Specifications"),

    ("7","Procurement, Vendor Approval and Manufacturing Process",
     "Advance Payment and Bank Guarantee Processing",
     "Financial transactions completed per purchase order terms. Vendor submits bank guarantee against advance payment before production starts.",
     "https://lauwtjunnji.weebly.com/uploads/1/0/1/7/10171621/fidic_-_conditions_of_contract_for_epc_(turnkey)_projects_(1999).pdf",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "https://pmri.in/epccompletion/",
     "Substation.docx; WBSETCL General Technical Specification (Turnkey)"),

    # ─── WORKFLOW 8 ───────────────────────────────────────────────────────────
    ("8","Manufacturing Execution, FAT Testing and Dispatch Process",
     "Manufacturing Kickoff – Production Planning",
     "Approved vendors begin production planning, allocate manufacturing resources, schedule production timelines and initiate fabrication.",
     "https://electrical-engineering-portal.com/checks-for-successful-substation-factory-acceptance-testing",
     "https://keentelengineering.com/substation-testing-lifecycle-fat-vs-sat",
     "https://electrical-engineering-portal.com/substation-equipment-type-testing-factory-site-acceptance-testing-fat-sat",
     "Substation.docx; WBSETCL General Technical Specification (Design, Engineering, Testing at Manufacturer)"),

    ("8","Manufacturing Execution, FAT Testing and Dispatch Process",
     "In Production – Equipment Manufacturing Process",
     "Vendors manufacture transformers, switchgear, panels, breakers, control systems and structures per approved drawings and purchase orders.",
     "https://electrical-engineering-portal.com/checks-for-successful-substation-factory-acceptance-testing",
     "https://electrical-engineering-portal.com/substation-equipment-type-testing-factory-site-acceptance-testing-fat-sat",
     "https://electrical-engineering-portal.com/transformer-factory-acceptance-tests-final-inspections",
     "Substation.docx; WBSETCL General Technical Specification (Fabrication, Galvanizing, Testing, Supply)"),

    ("8","Manufacturing Execution, FAT Testing and Dispatch Process",
     "Stage Inspection – In-Process Quality Verification",
     "Client and contractor inspectors visit manufacturing facility during production to verify quality at key manufacturing milestones.",
     "https://electrical-engineering-portal.com/substation-equipment-type-testing-factory-site-acceptance-testing-fat-sat",
     "https://keentelengineering.com/substation-testing-lifecycle-fat-vs-sat",
     "https://electrical-engineering-portal.com/checks-for-successful-substation-factory-acceptance-testing",
     "Substation.docx; WBSETCL General Technical Specification (Inspection Call 15 Days Prior)"),

    ("8","Manufacturing Execution, FAT Testing and Dispatch Process",
     "Factory Acceptance Testing (FAT)",
     "Final testing at manufacturer facility verifying electrical performance, operational functionality, safety compliance and design conformity before dispatch.",
     "https://electrical-engineering-portal.com/checks-for-successful-substation-factory-acceptance-testing",
     "https://keentelengineering.com/substation-testing-lifecycle-fat-vs-sat",
     "https://electrical-engineering-portal.com/res3/FAT-SAT-OF-electrical-and-automation-systems.pdf",
     "Substation.docx; WBSETCL General Technical Specification (FAT Testing Scope); OEU RFP – Commissioning and Testing Item"),

    ("8","Manufacturing Execution, FAT Testing and Dispatch Process",
     "Dispatch Clearance and Packing",
     "After FAT completion and client dispatch approval, equipment is packed, preserved and prepared for transport to project site.",
     "https://electrical-engineering-portal.com/checks-for-successful-substation-factory-acceptance-testing",
     "https://keentelengineering.com/substation-testing-lifecycle-fat-vs-sat",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "Substation.docx; WBSETCL (Supply and Delivery to Site Scope)"),

    # ─── WORKFLOW 9 ───────────────────────────────────────────────────────────
    ("9","Logistics, Transportation and Material Receipt Process",
     "Transport Planning and Route Survey",
     "Logistics teams plan transport routes, identify dimensional restrictions, obtain special transport permits and coordinate with authorities.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://prismecs.com/blog/understanding-the-lifecycle-of-epc-solutions-services",
     "Substation.docx; OEU RFP (Access Road Design – Contractor Responsibility Item 8)"),

    ("9","Logistics, Transportation and Material Receipt Process",
     "Equipment Dispatch from Vendor Facility",
     "Equipment dispatched from manufacturing facility with complete documentation including test reports, packing list and dispatch advices.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://keentelengineering.com/substation-testing-lifecycle-fat-vs-sat",
     "Substation.docx; WBSETCL General Technical Specification (Supply and Delivery of Cables/Equipment)"),

    ("9","Logistics, Transportation and Material Receipt Process",
     "In-Transit Monitoring and Tracking",
     "Logistics team monitors equipment movement from vendor to site, tracks shipment status and coordinates with transporters.",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://prismecs.com/blog/understanding-the-lifecycle-of-epc-solutions-services",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "Substation.docx"),

    ("9","Logistics, Transportation and Material Receipt Process",
     "Site Unloading and Placement",
     "Heavy equipment unloaded at site using cranes, placed in designated storage or directly on foundations as per erection sequence.",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "Substation.docx; Valard – 10 Stages (Electrical Equipment installation via cranes); WBSETCL (Transformer unloading at site)"),

    # ─── WORKFLOW 10 ──────────────────────────────────────────────────────────
    ("10","Material Receipt, Inspection and Installation Release Process",
     "Site Preparation for Material Receipt",
     "Site teams verify storage space, unloading equipment readiness, manpower and material handling arrangements before delivery.",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://projectmanagement123.com/project-completion-and-handover-procedure/",
     "Substation.docx; Valard – 10 Stages of Substation Construction"),

    ("10","Material Receipt, Inspection and Installation Release Process",
     "Material Unloading and Receipt",
     "Materials unloaded at site, verified against dispatch documents, packing lists and purchase orders for quantity and identity.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "Substation.docx"),

    ("10","Material Receipt, Inspection and Installation Release Process",
     "Incoming Inspection and Quality Verification",
     "Quality team inspects received equipment for physical damage, completeness, documentation correctness and conformance to specifications.",
     "https://electrical-engineering-portal.com/substation-equipment-type-testing-factory-site-acceptance-testing-fat-sat",
     "https://keentelengineering.com/substation-testing-lifecycle-fat-vs-sat",
     "https://electrical-engineering-portal.com/checks-for-successful-substation-factory-acceptance-testing",
     "Substation.docx; WBSETCL General Technical Specification (Equipment Workmanship Standards)"),

    ("10","Material Receipt, Inspection and Installation Release Process",
     "SDR / Claim Management – Discrepancy Resolution",
     "If discrepancies found (damage, shortage, wrong material), SDR (Site Discrepancy Report) raised and claim initiated with vendor/insurer.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "https://www.pillsburylaw.com/a/web/157254/EPC-Agreement-Provisions.pdf",
     "Substation.docx"),

    ("10","Material Receipt, Inspection and Installation Release Process",
     "Storage and Inventory Management",
     "Accepted materials stored properly in designated areas, inventory records updated and materials preserved as per manufacturer requirements.",
     "https://blog.projectmaterials.com/category/epc-projects/procurement-logistics/project-procurement-documents",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "Substation.docx"),

    ("10","Material Receipt, Inspection and Installation Release Process",
     "Released for Installation",
     "Materials formally released from inventory to field teams for installation after passing inspection and quality verification.",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://rkstrainings.com/what-is-project-management-in-epc/",
     "Substation.docx"),

    # ─── WORKFLOW 11 ──────────────────────────────────────────────────────────
    ("11","Civil Construction and Structural Readiness Process",
     "Site Clearing, Grading and Levelling",
     "Construction teams perform land clearing, grubbing, grading and levelling to prepare site to required elevation per civil drawings.",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx; Valard – 10 Stages (Brushing & Site Clearing; Substation Pad Construction)"),

    ("11","Civil Construction and Structural Readiness Process",
     "Below Grade Works – Cable Trenches, Conduits, Ground Grid",
     "Underground conduits, cable trenches, draw boxes and earth mat conductors installed below ground level per approved drawings.",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://electra.cigre.org/311-august-2020/technical-brochures/guidelines-for-safe-work-methods-in-substations.html",
     "Substation.docx; Valard – 10 Stages (Below Grade Facilities); OEU RFP – Underground Raceway; WBSETCL (Earth Mat)"),

    ("11","Civil Construction and Structural Readiness Process",
     "Foundation Construction",
     "Concrete foundations for equipment, structural steel, control room and buildings constructed per approved foundation drawings.",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electra.cigre.org/311-august-2020/technical-brochures/guidelines-for-safe-work-methods-in-substations.html",
     "Substation.docx; Valard – 10 Stages (Foundations); OEU RFP – Foundation Design; WBSETCL (Foundation of Substation Structure)"),

    ("11","Civil Construction and Structural Readiness Process",
     "Control Room and Buildings Construction",
     "Control room building, store shed, DG shed, pump house and other civil structures constructed as per architectural drawings.",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electra.cigre.org/311-august-2020/technical-brochures/guidelines-for-safe-work-methods-in-substations.html",
     "Substation.docx; Eskom Dinaledi Civil SOW (New Access Control Building); WBSETCL (Control Room Building Design)"),

    ("11","Civil Construction and Structural Readiness Process",
     "Drainage, Fencing and Stone Verge",
     "Stormwater drainage system, security fencing, stone verge (HV yard stone) and site perimeter works completed as per civil drawings.",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://electra.cigre.org/311-august-2020/technical-brochures/guidelines-for-safe-work-methods-in-substations.html",
     "Substation.docx; Eskom Dinaledi Civil SOW (Outer Fence; Stone Verge; Refurbishment of Drainage); OEU RFP – Screen Wall"),

    ("11","Civil Construction and Structural Readiness Process",
     "Civil Readiness Check – Structural Work Complete",
     "Formal inspection confirms all civil and structural works are complete and ready for equipment erection to begin.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-2-pre-commissioning-inspections/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx"),

    # ─── WORKFLOW 12 ──────────────────────────────────────────────────────────
    ("12","Equipment Erection, Mechanical Installation and Cabling Readiness Process",
     "Prerequisite Verification – Civil and Materials Ready",
     "Confirm all civil foundations complete and all required equipment and materials inspected, accepted and released from inventory.",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-2-pre-commissioning-inspections/",
     "Substation.docx; Valard – 10 Stages (Electrical Equipment)"),

    ("12","Equipment Erection, Mechanical Installation and Cabling Readiness Process",
     "Structural Steel Erection",
     "Structural support steel (lattice, H-beam or tubular) erected and secured to foundations to support switchyard equipment.",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electra.cigre.org/311-august-2020/technical-brochures/guidelines-for-safe-work-methods-in-substations.html",
     "Substation.docx; Valard – 10 Stages (Structural Support Steel); WBSETCL (Fabrication, Galvanizing, Erection of Structures)"),

    ("12","Equipment Erection, Mechanical Installation and Cabling Readiness Process",
     "Power Transformer and Major Equipment Installation",
     "Power transformers, circuit breakers, reactors, CTs, PTs and other major equipment installed on foundations using cranes.",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical-engineering-portal.com/transformer-factory-acceptance-tests-final-inspections",
     "Substation.docx; Valard – 10 Stages (Electrical Equipment); WBSETCL (Power Transformer Erection & Commissioning); OEU RFP (OEU provides Transformers & Breakers)"),

    ("12","Equipment Erection, Mechanical Installation and Cabling Readiness Process",
     "Bus Bar and Conductor Installation",
     "Flexible and rigid bus bars, conductors, insulators, clamps and connectors installed to connect all switchyard equipment.",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://keentelengineering.com/ieee-compliant-ehv-hv-mv-substation-design-services-by-keentel-engineering",
     "Substation.docx; Valard – 10 Stages (Electrical Bus Work); WBSETCL (Clamps, Connectors, Hardware Fittings)"),

    ("12","Equipment Erection, Mechanical Installation and Cabling Readiness Process",
     "Mechanical Completion Check",
     "Formal inspection confirms all equipment erection and mechanical installation is complete per drawings before cabling begins.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-2-pre-commissioning-inspections/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx"),

    # ─── WORKFLOW 13 ──────────────────────────────────────────────────────────
    ("13","Cabling, Termination, Testing and SAS Readiness Process",
     "Power and Control Cable Laying",
     "Power cables and control cables pulled through conduits and cable trays from control building to all switchyard equipment.",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx; Valard – 10 Stages (Cable Pulling & Terminating); WBSETCL (Power Cable, Control Cable Supply & Laying)"),

    ("13","Cabling, Termination, Testing and SAS Readiness Process",
     "Cable Termination at Equipment and Panels",
     "All cables terminated at equipment terminals, control panels, relay panels and marshalling boxes per approved wiring diagrams.",
     "https://www.substationfaults.com/electrical-substation-construction/",
     "https://electrical-engineering-portal.com/power-substation-project-design-construction-erection-commissioning",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx; Valard – 10 Stages (Cable Pulling & Terminating); OEU RFP (Point-to-point panel wiring diagrams)"),

    ("13","Cabling, Termination, Testing and SAS Readiness Process",
     "Point-to-Point Continuity Testing",
     "Technicians test every cable connection end-to-end for continuity, correct routing, labeling and correct termination against wiring diagrams.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-2-pre-commissioning-inspections/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx; OEU RFP (Point-to-point panel wiring diagrams at 90%)"),

    ("13","Cabling, Termination, Testing and SAS Readiness Process",
     "SAS Panel Installation and Configuration",
     "Substation Automation System (SAS) panels, IEDs (Intelligent Electronic Devices) and communication equipment installed and configured.",
     "https://instrumentationtools.com/scada-for-substation-automation/",
     "https://seclab.illinois.edu/wp-content/uploads/2011/03/iec61850-intro.pdf",
     "https://library.e.abb.com/public/5ea2620c3dec4376a1540fc2b07a18b7/IEC%2061850%20Overview_Self.pdf",
     "Substation.docx; WBSETCL (Control & Relay Panel – Supply, Erection, Testing & Commissioning); OEU RFP (Relay & Control Panels)"),

    ("13","Cabling, Termination, Testing and SAS Readiness Process",
     "SAS Readiness Check",
     "Formal confirmation that all cabling, terminations and SAS panel installations are complete and ready for functional testing.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-4-scada-and-comms-systems",
     "https://instrumentationtools.com/scada-for-substation-automation/",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx"),

    # ─── WORKFLOW 14 ──────────────────────────────────────────────────────────
    ("14","SAS / SCADA Integration, Functional Testing and Pre-Commissioning Readiness Process",
     "IED Configuration and Logic Programming",
     "Protection and automation engineers configure IEDs, program protection logic, set relay parameters per coordination study.",
     "https://seclab.illinois.edu/wp-content/uploads/2011/03/iec61850-intro.pdf",
     "https://library.e.abb.com/public/5ea2620c3dec4376a1540fc2b07a18b7/IEC%2061850%20Overview_Self.pdf",
     "https://instrumentationtools.com/scada-for-substation-automation/",
     "Substation.docx; OEU RFP (Relay settings in AcSELerator format; Relay Coordination Study using ETAP)"),

    ("14","SAS / SCADA Integration, Functional Testing and Pre-Commissioning Readiness Process",
     "SCADA Integration and Communication Testing",
     "SCADA system integration tested to verify all signals, alarms, controls and measurements communicate correctly between field and control centre.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-4-scada-and-comms-systems",
     "https://instrumentationtools.com/scada-for-substation-automation/",
     "https://seclab.illinois.edu/wp-content/uploads/2011/03/iec61850-intro.pdf",
     "Substation.docx; WBSETCL (PLCC/Microwave Teleprotection Commissioning); OEU RFP (Communications Block Diagram)"),

    ("14","SAS / SCADA Integration, Functional Testing and Pre-Commissioning Readiness Process",
     "Functional Testing of Protection Schemes",
     "All protection schemes (differential, overcurrent, earth fault, busbar, breaker failure) tested functionally by secondary injection.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-2-pre-commissioning-inspections/",
     "https://eepower.com/technical-articles/substation-commissioning-and-testing-part-3-field-testing/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx; OEU RFP (Relay Coordination Study using ETAP)"),

    ("14","SAS / SCADA Integration, Functional Testing and Pre-Commissioning Readiness Process",
     "HMI and Local Control Testing",
     "Local control panel HMI, mimic display, annunciator, alarm system and local/remote switching tested for correct operation.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-4-scada-and-comms-systems",
     "https://instrumentationtools.com/scada-for-substation-automation/",
     "https://mbcontrol.com/understanding-substation-automation-systems/",
     "Substation.docx; WBSETCL (Control & Relay Panel Commissioning)"),

    ("14","SAS / SCADA Integration, Functional Testing and Pre-Commissioning Readiness Process",
     "Pre-Commissioning Readiness Declaration",
     "All SAS and functional test results reviewed. Pre-commissioning readiness certificate issued confirming system ready for energization tests.",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx"),

    # ─── WORKFLOW 15 ──────────────────────────────────────────────────────────
    ("15","Pre-Commissioning Testing, System Validation and Commissioning Readiness Process",
     "Insulation Resistance (IR) Testing",
     "Insulation resistance tested on all cables, transformers, switchgear and equipment to verify insulation integrity before energization.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-2-pre-commissioning-inspections/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx; OEU RFP (Equipment Tested in Presence of City Representative)"),

    ("15","Pre-Commissioning Testing, System Validation and Commissioning Readiness Process",
     "CT / PT Ratio, Polarity and Burden Testing",
     "Current transformers and voltage transformers tested for ratio accuracy, polarity correctness, excitation and burden compliance.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testing-part-3-field-testing/",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-2-pre-commissioning-inspections/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx"),

    ("15","Pre-Commissioning Testing, System Validation and Commissioning Readiness Process",
     "Protection Relay Secondary Injection Testing",
     "All protection relays tested using secondary injection equipment to verify pickup settings, timing, tripping and relay coordination.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testing-part-3-field-testing/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://elliotengineeringinc.com/testing-and-commissioning/",
     "Substation.docx; OEU RFP (Relay Settings in AcSELerator; Relay Coordination using ETAP)"),

    ("15","Pre-Commissioning Testing, System Validation and Commissioning Readiness Process",
     "Circuit Breaker Timing and Mechanical Testing",
     "Circuit breaker operations tested for timing, contact resistance, mechanical operation, coil profiling and gas/vacuum checks.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testing-part-3-field-testing/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx"),

    ("15","Pre-Commissioning Testing, System Validation and Commissioning Readiness Process",
     "Transformer Differential and REF Stability Testing",
     "Transformer differential protection and restricted earth fault (REF) protection tested for stability and correct operation before energization.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testing-part-3-field-testing/",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-2-pre-commissioning-inspections/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx"),

    ("15","Pre-Commissioning Testing, System Validation and Commissioning Readiness Process",
     "Ground Grid Continuity and Earthing Verification",
     "Earth mat continuity tested with low-ohm injection. All equipment earthing connections verified as per IEEE Std. 80/81.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-2-pre-commissioning-inspections/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx; OEU RFP (IEEE Std. 80 – Grounding Reference); WBSETCL (Earthing System Commissioning)"),

    ("15","Pre-Commissioning Testing, System Validation and Commissioning Readiness Process",
     "Punch List Identification and Rectification",
     "All outstanding deficiencies from testing identified, punch list prepared, and all items rectified before commissioning readiness declared.",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://pmri.in/epccompletion/",
     "Substation.docx; OEU RFP (Substantial Completion – List of Items to be Corrected)"),

    ("15","Pre-Commissioning Testing, System Validation and Commissioning Readiness Process",
     "Commissioning Readiness Certificate Issued",
     "All pre-commissioning tests completed and documented. Commissioning readiness certificate signed off by client and contractor teams.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx; OEU RFP (Final Inspection – Written Certification); WBSETCL (Commissioning Plan)"),

    # ─── WORKFLOW 16 ──────────────────────────────────────────────────────────
    ("16","Final Commissioning, Initial Charging and Energization Readiness Process",
     "Pre-Commissioning Completion Verification",
     "Commissioning team confirms all pre-commissioning tests passed, all punch list items cleared and all systems validated before live work begins.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx; OEU RFP – Final Inspection Section"),

    ("16","Final Commissioning, Initial Charging and Energization Readiness Process",
     "External Clearances – Grid / SLDC / Regulatory Approvals",
     "Coordination with Grid/SLDC for synchronization approval, regulatory body clearances and all external operational authorizations obtained.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx"),

    ("16","Final Commissioning, Initial Charging and Energization Readiness Process",
     "Initial Charging of Equipment – Step-by-Step Energization",
     "Controlled step-by-step energization starting from low voltage components progressively to high voltage equipment per energization sequence.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx; Valard – 10 Stages (Testing & Commissioning); OEU RFP (Commissioning and Testing)"),

    ("16","Final Commissioning, Initial Charging and Energization Readiness Process",
     "Protection Selectivity Verification Under Live Conditions",
     "Protection relay operation verified under live energized conditions. Inrush monitoring, load behavior and protection selectivity confirmed.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testing-part-3-field-testing/",
     "https://elliotengineeringinc.com/testing-and-commissioning/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx"),

    ("16","Final Commissioning, Initial Charging and Energization Readiness Process",
     "Energization Readiness Confirmed",
     "All commissioning checks completed. Substation declared energization ready. Full voltage applied across all equipment.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "Substation.docx; OEU RFP (Equipment Systems Tested and Operational)"),

    # ─── WORKFLOW 17 ──────────────────────────────────────────────────────────
    ("17","Final Energization and Grid Synchronization Process",
     "Grid Authorization Received",
     "Grid operator (SLDC/utility) issues formal authorization for permanent connection and synchronization with the live power grid.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx"),

    ("17","Final Energization and Grid Synchronization Process",
     "Charge and Synchronize – Permanent Grid Connection",
     "Substation charged and synchronized with live grid. Electrical connection between new substation and power grid officially established.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx; Valard – 10 Stages (Testing & Commissioning – Substation turned on)"),

    ("17","Final Energization and Grid Synchronization Process",
     "Load Flow Verification",
     "Engineers verify correct power flow through transformers, busbars, feeders and outgoing lines. Load distribution and system balance confirmed.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testing-part-3-field-testing/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx"),

    ("17","Final Energization and Grid Synchronization Process",
     "Metering and Billing Meter Verification",
     "Energy meters, billing meters, measurement systems, CTs and VTs validated for accurate operational measurement and revenue metering.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testing-part-3-field-testing/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx"),

    # ─── WORKFLOW 18 ──────────────────────────────────────────────────────────
    ("18","Trial Run and Performance Stabilization Process",
     "Trial Operation Period",
     "Substation operated under normal and varying load conditions for a defined period to verify sustained performance and reliability.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://electrical4learning.blogspot.com/2024/11/method-statement-for-testing-and-commissioning-of-substation-equipments.html",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx"),

    ("18","Trial Run and Performance Stabilization Process",
     "Performance Monitoring – Live Data Collection",
     "All operational parameters monitored: voltage stability, current flow, transformer loading, protection operation, alarms, SCADA data.",
     "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12431182/",
     "https://instrumentationtools.com/scada-for-substation-automation/",
     "https://mbcontrol.com/understanding-substation-automation-systems/",
     "Substation.docx; WBSETCL (DGA Test Before Commissioning)"),

    ("18","Trial Run and Performance Stabilization Process",
     "Defect Identification and Correction During Trial Run",
     "Any defects or anomalies identified during trial run are recorded, investigated and corrected before handover.",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "Substation.docx"),

    ("18","Trial Run and Performance Stabilization Process",
     "Performance Stabilization Confirmed",
     "System declared stable after successful trial operation. All performance benchmarks met. Substation ready for formal handover.",
     "https://eepower.com/technical-articles/substation-commissioning-and-testingpart-1-scope-and-workflow/",
     "https://pmri.in/epccompletion/",
     "https://powersynchro.com/substation-commissioning-checklist/",
     "Substation.docx"),

    # ─── WORKFLOW 19 ──────────────────────────────────────────────────────────
    ("19","Project Closure, Client Acceptance and Final Handover Process",
     "Punch List Final Completion",
     "All outstanding items from commissioning and trial run identified on final punch list are completely resolved before handover.",
     "https://pmri.in/epccompletion/",
     "https://projectmanagement123.com/project-completion-and-handover-procedure/",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "Substation.docx; OEU RFP (Substantial Completion – Items to be Completed or Corrected)"),

    ("19","Project Closure, Client Acceptance and Final Handover Process",
     "Client Walk-through and Acceptance Inspection",
     "Client and contractor jointly inspect all works. Client verifies compliance with contract scope, specifications and quality standards.",
     "https://pmri.in/epccompletion/",
     "https://projectmanagement123.com/project-completion-and-handover-procedure/",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "Substation.docx; OEU RFP (Final Inspection – City conducts inspection to verify completion status)"),

    ("19","Project Closure, Client Acceptance and Final Handover Process",
     "As-Built Documentation Handover",
     "Final as-built drawings, test reports, manuals, warranties and operation documentation formally handed over to client.",
     "https://projectmanagement123.com/project-completion-and-handover-procedure/",
     "https://pmri.in/epccompletion/",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "Substation.docx; OEU RFP (Record Drawing in AutoCAD 2018 + Hard Copy; Warranties & Operational Manuals); WBSETCL (Commissioning Plan)"),

    ("19","Project Closure, Client Acceptance and Final Handover Process",
     "Certificate of Completion / Provisional Acceptance Certificate (PAC)",
     "Client issues Completion Certificate or PAC (Provisional Acceptance Certificate) marking official project handover and start of DLP.",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://pmri.in/epccompletion/",
     "Substation.docx; OEU RFP (Certificate of Substantial Completion); FIDIC Silver Book Reference"),

    ("19","Project Closure, Client Acceptance and Final Handover Process",
     "Contractor Closeout Submittals",
     "Contractor submits closeout package: completed submittals, evidence of subcontractor payments, warranties and operation manuals.",
     "https://projectmanagement123.com/project-completion-and-handover-procedure/",
     "https://pmri.in/epccompletion/",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "OEU White Substation RFP – Contractor's Closeout Submittals Section (Page 7-8)"),

    # ─── WORKFLOW 20 ──────────────────────────────────────────────────────────
    ("20","Defect Liability Period (DLP), Warranty Support and Final Acceptance Process",
     "DLP Period Commencement",
     "DLP begins from date of Completion Certificate/PAC. Contractor remains responsible for rectifying defects for DLP duration (typically 12-24 months).",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "Substation.docx; FIDIC Silver Book – Clause 11"),

    ("20","Defect Liability Period (DLP), Warranty Support and Final Acceptance Process",
     "Defect Attendance – Identification and Repair",
     "Client notifies contractor of defects in writing. Contractor attends, investigates and rectifies defects at no extra cost within agreed timeframe.",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "https://www.turtons.com/blog/what-is-the-defects-liability-period",
     "Substation.docx; OEU RFP (Work Incomplete or Defective – City Notifies Contractor in Writing)"),

    ("20","Defect Liability Period (DLP), Warranty Support and Final Acceptance Process",
     "Recurring Defect Investigation and Permanent Resolution",
     "Recurring defects investigated for root cause. Design modifications, material replacements or procedural changes implemented for permanent resolution.",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://www.turtons.com/blog/what-is-the-defects-liability-period",
     "Substation.docx"),

    ("20","Defect Liability Period (DLP), Warranty Support and Final Acceptance Process",
     "Warranty Claims Management",
     "Equipment warranty claims raised with manufacturers for defective components. Replacement or repair managed within warranty period.",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "https://lauwtjunnji.weebly.com/uploads/1/0/1/7/10171621/fidic_-_conditions_of_contract_for_epc_(turnkey)_projects_(1999).pdf",
     "Substation.docx; OEU RFP (Warranties and Operational Manuals – 2 Copies at Closeout)"),

    # ─── WORKFLOW 21 ──────────────────────────────────────────────────────────
    ("21","Final Acceptance Certificate (FAC), Contract Closure and Project Closeout Process",
     "All DLP Defects Rectified – Final Inspection Request",
     "Contractor confirms all DLP defects rectified and requests final inspection from client for issuance of Final Acceptance Certificate (FAC).",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://pmri.in/epccompletion/",
     "Substation.docx; OEU RFP (Final Inspection Section – Contractor submits written certification)"),

    ("21","Final Acceptance Certificate (FAC), Contract Closure and Project Closeout Process",
     "Final Acceptance Certificate (FAC) Issuance",
     "Client issues FAC after confirming all defects resolved and project performed satisfactorily throughout DLP. Contractor released from further liability.",
     "https://relgrow.com/resources/dlp-full-form-in-construction/",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "Substation.docx; FIDIC Silver Book – Clause 11.9 (Performance Certificate)"),

    ("21","Final Acceptance Certificate (FAC), Contract Closure and Project Closeout Process",
     "Final Payment and Retention Release",
     "Final payment processed. Retention amounts held during DLP released to contractor. Performance bonds and bank guarantees returned.",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "https://lauwtjunnji.weebly.com/uploads/1/0/1/7/10171621/fidic_-_conditions_of_contract_for_epc_(turnkey)_projects_(1999).pdf",
     "https://www.mastt.com/blogs/defects-liability-period",
     "Substation.docx; OEU RFP (Evidence of Payment to Subcontractors); FIDIC Silver Book – Final Payment Clause"),

    ("21","Final Acceptance Certificate (FAC), Contract Closure and Project Closeout Process",
     "Contract Closure and Project Closeout",
     "All contractual obligations fulfilled. Project closed in management systems. Lessons learned documented. Project formally archived.",
     "https://projectmanagement123.com/project-completion-and-handover-procedure/",
     "https://pmri.in/epccompletion/",
     "https://www.pmi.org/learning/library/realizing-engineering-procurement-construction-projects-7173",
     "Substation.docx; OEU RFP – Full Deliverables Section"),

    ("21","Final Acceptance Certificate (FAC), Contract Closure and Project Closeout Process",
     "Rework Loop – Unresolved Issues Resolution",
     "If FAC not granted due to remaining issues, rework loop activated. Issues re-investigated, corrected and final inspection repeated.",
     "https://constructionlawmadeeasy.com/construction-law/chapter-10/defects-liability-period/",
     "https://www.mastt.com/blogs/defects-liability-period",
     "https://projectmanagement123.com/project-completion-and-handover-procedure/",
     "Substation.docx; OEU RFP (Contractor shall remedy deficiencies – Second Written Notice of Substantial Completion)"),
]

# ── Write Headers ─────────────────────────────────────────────────────────────
thin = Side(style='thin')
border = Border(left=thin, right=thin, top=thin, bottom=thin)

header_font = Font(bold=True, size=11)
header_align = Alignment(horizontal='center', vertical='center', wrap_text=True)

for col_num, header in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col_num, value=header)
    cell.font = header_font
    cell.alignment = header_align
    cell.border = border

# ── Write Data ────────────────────────────────────────────────────────────────
wrap = Alignment(vertical='top', wrap_text=True)

for row_num, row_data in enumerate(data, 2):
    for col_num, value in enumerate(row_data, 1):
        cell = ws.cell(row=row_num, column=col_num, value=value)
        cell.alignment = wrap
        cell.border = border
        # Make URLs clickable
        if col_num in (5, 6, 7) and value.startswith("http"):
            cell.hyperlink = value
            cell.font = Font(color="0563C1", underline="single")

# ── Column Widths ─────────────────────────────────────────────────────────────
col_widths = [14, 38, 42, 52, 55, 55, 55, 60]
for i, width in enumerate(col_widths, 1):
    ws.column_dimensions[get_column_letter(i)].width = width

# ── Row Height ────────────────────────────────────────────────────────────────
ws.row_dimensions[1].height = 30
for row_num in range(2, len(data) + 2):
    ws.row_dimensions[row_num].height = 55

# ── Freeze Top Row ────────────────────────────────────────────────────────────
ws.freeze_panes = "A2"

# ── Auto Filter ───────────────────────────────────────────────────────────────
ws.auto_filter.ref = f"A1:H{len(data)+1}"

# ── Save ──────────────────────────────────────────────────────────────────────
output_path = "/home/user/Harrsh25/Substation_Workflow_Module_Guide.xlsx"
wb.save(output_path)
print(f"Excel saved: {output_path}")
print(f"Total rows: {len(data)}")
print(f"Total workflows: {len(set(r[0] for r in data))}")
