const H = require('../tools/lib');
module.exports = async () => {
  const t = H.T('Registration validation & new fields');
  const { b, p, errors } = await H.open();
  await H.go(p, '/productivity/vendor-management/registry');
  await H.click(p, 'Register vendor', { dlg: false });
  // Labour contractor with bad data
  await H.click(p, 'LabourSupplies workers / manpower for site work', { exact: false }).catch(async () => { await p.click('[role=dialog] button:has-text("Labour")'); });
  await H.fill(p, 'Company / trade name', 'Test Infra Co');
  await p.click('[role=dialog] button[aria-pressed]:has-text("Civil")');
  await H.fill(p, 'GSTIN', '27AAKCT1234M1Z5');
  await H.fill(p, 'Contact person', 'Asha Rao');
  await H.fill(p, 'Email', 'asha@testinfra.in');
  await H.fill(p, 'Phone', '12345');
  await H.fill(p, 'PIN code', '4110');
  await H.fill(p, 'Website', 'not a site');
  await H.fill(p, 'Labour licence no. (CLRA)', 'x');
  await H.fill(p, 'PF establishment code', 'ABC');
  await H.fill(p, 'ESI code', '123');
  await H.fill(p, 'Workforce strength', '-5');
  await H.fill(p, 'Account no.', '12ab');
  await H.click(p, 'Save draft');
  let a = (await H.alerts(p)).join(' | ');
  t.ok(/valid phone/.test(a), 'phone format error shown');
  t.ok(/PIN code must be 6 digits/.test(a), 'PIN error shown');
  t.ok(/valid website/.test(a), 'website error shown');
  t.ok(/CLRA|6.30 chars/.test(a), 'CLRA error shown');
  t.ok(/PF code/.test(a), 'PF error shown');
  t.ok(/ESI code must be 17 digits/.test(a), 'ESI error shown');
  t.ok(/Workforce can't be below 1/.test(a), 'workforce range error');
  t.ok(/Account number must be 9/.test(a), 'account number error');
  t.ok(/account holder/i.test(a), 'holder required when bank entered');
  t.ok(/licence expiry/i.test(a), 'licence expiry required when licence given');
  t.ok(await H.dialogs(p) === 1, 'dialog stays open while invalid');
  // fix everything
  await H.fill(p, 'Phone', '+91 98220 41152');
  await H.fill(p, 'PIN code', '411026');
  await H.fill(p, 'Website', 'www.testinfra.in');
  await H.fill(p, 'Labour licence no. (CLRA)', 'CLRA/PUN/2026/0099');
  await H.fill(p, 'Licence valid till', '2027-12-31');
  await H.fill(p, 'PF establishment code', 'PUPUN1234567000');
  await H.fill(p, 'ESI code', '33000412210009999');
  await H.fill(p, 'Workforce strength', '120');
  await H.fill(p, 'Account holder name', 'Test Infra Co Pvt Ltd');
  await H.fill(p, 'Bank', 'HDFC Bank');
  await H.fill(p, 'Account no.', '50200012345678');
  await H.fill(p, 'IFSC', 'HDFC0001234');
  await H.click(p, 'Save draft');
  await H.sleep(400);
  const opened = await H.text(p);
  t.ok(/Test Infra Co/.test(opened) && /VEN-/.test(opened), 'saved once valid (new vendor record opens)');
  await p.keyboard.press('Escape'); await H.sleep(300);
  const st = await H.store(p);
  const v = st && st.vendors.find(x => x.name === 'Test Infra Co');
  t.ok(v, 'vendor persisted');
  t.ok(v && v.pin === '411026' && v.country === 'India' && v.website === 'www.testinfra.in', 'PIN/country/website persisted');
  t.ok(v && v.bankAccounts[0] && v.bankAccounts[0].holder === 'Test Infra Co Pvt Ltd' && v.bankAccounts[0].status === 'Unverified', 'bank holder + Unverified status persisted');
  t.ok(v && v.contractor && v.contractor.pfCode === 'PUPUN1234567000', 'contractor codes persisted');
  // foreign vendor: GSTIN not required, tax id required
  await H.click(p, 'Register vendor', { dlg: false });
  await H.fill(p, 'Company / trade name', 'Gulf Steel LLC');
  await p.click('[role=dialog] button[aria-pressed]:has-text("Steel")');
  await H.pick(p, 'Country', 'United Arab Emirates');
  await H.fill(p, 'Contact person', 'Omar');
  await H.fill(p, 'Email', 'omar@gulfsteel.ae');
  await H.click(p, 'Save draft');
  a = (await H.alerts(p)).join(' | ');
  t.ok(/tax \/ VAT/.test(a) && !/GSTIN/.test(a), 'foreign vendor needs Tax/VAT, not GSTIN');
  await H.fill(p, 'Tax / VAT registration no.', 'TRN100234567800003');
  await H.fill(p, 'Postal code', '00000');
  await H.click(p, 'Save draft');
  const st2 = await H.store(p);
  const g = st2.vendors.find(x => x.name === 'Gulf Steel LLC');
  t.ok(g && g.country === 'United Arab Emirates' && g.currency === 'AED', 'foreign vendor saved with AED currency');
  t.ok(errors.length === 0, 'no page errors: ' + errors.join('; '));
  await b.close(); return t.done();
};
