const H = require('../tools/lib');
module.exports = async () => {
  const t = H.T('Labour rate / contractor advance / retention release validation');
  const { b, p, errors } = await H.open();
  // --- labour rate
  await H.go(p, '/productivity/contract-labor/labor-rates');
  await H.click(p, 'New rate', { dlg: false });
  t.ok(await H.disabled(p, 'Submit for approval') === true, 'empty rate card cannot be submitted');
  await H.fill(p, 'Trade', 'Test Welder');
  await H.fill(p, 'Statutory minimum wage / day (₹)', '700');
  await H.fill(p, 'Billing rate / day (₹)', '600');
  await H.fill(p, 'Overtime multiplier', '5');
  let a = (await H.alerts(p)).join(' | ');
  t.ok(/below the statutory minimum wage/.test(a), 'rate below minimum wage is blocked');
  t.ok(/OT multiplier can't exceed 3/.test(a), 'OT multiplier > 3 rejected');
  t.ok(await H.disabled(p, 'Submit for approval') === true, 'submit blocked while invalid');
  await H.fill(p, 'Billing rate / day (₹)', '950');
  await H.fill(p, 'Overtime multiplier', '2');
  t.ok(await H.disabled(p, 'Submit for approval') === false, 'valid card can be submitted');
  await H.click(p, 'Submit for approval'); await H.sleep(300);
  let st = await H.store(p);
  const lr = st.laborRates.find(x => x.trade === 'Test Welder');
  t.ok(lr && lr.status === 'Pending Approval' && lr.rate === 950, 'rate card saved as Pending Approval');
  await H.click(p, 'New rate', { dlg: false });
  await H.fill(p, 'Trade', 'Test Welder');
  t.ok(/already exists/.test(await H.text(p)), 'duplicate trade/zone/contractor card is flagged');
  t.ok(await H.disabled(p, 'Submit for approval') === true, 'duplicate card blocked');
  await p.keyboard.press('Escape'); await H.sleep(300);
  // --- contractor advance
  await H.go(p, '/productivity/contract-labor/retention');
  await H.click(p, 'Record advance', { dlg: false });
  t.ok(/Up to/.test(await H.text(p)), 'mobilisation advance limit shown');
  await H.fill(p, 'Amount (₹)', '999999999');
  await H.fill(p, 'Date paid', '2099-01-01');
  a = (await H.alerts(p)).join(' | ');
  t.ok(/exceed the contract value|mobilisation advance/.test(a), 'advance above contract/limit rejected');
  t.ok(/can't be in the future/.test(a), 'future payment date rejected');
  await H.pick(p, 'Type', 'Secured advance (materials)');
  await H.fill(p, 'Amount (₹)', '250000');
  await H.fill(p, 'Date paid', new Date().toISOString().slice(0, 10));
  t.ok(await H.disabled(p, 'Save') === true, 'payment reference is mandatory');
  await H.fill(p, 'Payment ref / BG no.', 'UTR123456');
  t.ok(await H.disabled(p, 'Save') === false, 'valid advance can be saved');
  const before = (await H.store(p)).contracts.find(c => c.id === 'CTR-001').advanceAmount;
  await H.click(p, 'Save'); await H.sleep(300);
  st = await H.store(p);
  t.ok(st.contracts.find(c => c.id === 'CTR-001').advanceAmount === before + 250000, 'advance added to contract');
  // --- retention release
  await H.click(p, 'Request retention release', { dlg: false });
  await H.pick(p, 'Basis', 'Against bank guarantee');
  await H.fill(p, 'Amount (₹)', '999999999');
  a = (await H.alerts(p)).join(' | ');
  t.ok(/Exceeds available retention/.test(a), 'release above available retention rejected inline');
  await H.fill(p, 'Amount (₹)', '1000');
  t.ok(await H.disabled(p, 'Raise request') === true, 'BG reference required for BG-backed release');
  await H.fill(p, 'BG reference', 'BG/ICICI/2026/551');
  t.ok(await H.disabled(p, 'Raise request') === false, 'valid release can be raised');
  await H.click(p, 'Raise request'); await H.sleep(300);
  st = await H.store(p);
  t.ok(st.retentionReleases.some(r => r.amount === 1000 && r.status === 'Due'), 'release request saved');
  t.ok(errors.length === 0, 'no page errors: ' + errors.join('; '));
  await b.close(); return t.done();
};
