const H = require('../tools/lib');
module.exports = async () => {
  const t = H.T('RFQ creation + quotation (FX, validity, lines)');
  const { b, p, errors } = await H.open();
  await H.go(p, '/productivity/vendor-management/rfq');
  await H.click(p, 'New RFQ', { dlg: false });
  t.ok(await H.disabled(p, 'Save & compose e-mail') === true, 'empty RFQ cannot be saved');
  await H.fill(p, 'Title', 'Test RFQ cement');
  await H.fill(p, 'Quotes due (order deadline)', '2020-01-01');
  t.ok(/must be in the future/.test((await H.alerts(p)).join(' ')), 'past due date rejected');
  const d = new Date(); d.setDate(d.getDate() + 10); const due = d.toISOString().slice(0, 10);
  await H.fill(p, 'Quotes due (order deadline)', due);
  const inp = await p.$$('[role=dialog] .space-y-2.p-3 input');
  await inp[0].fill('OPC 53 cement'); await inp[2].fill('-5'); await H.sleep(100);
  t.ok(/quantity must be greater than 0/.test(await H.text(p)), 'negative line qty rejected');
  await inp[2].fill('500'); await inp[3].fill(new Date().toISOString().slice(0, 10)); await H.sleep(100);
  t.ok(/before quotes are due/.test(await H.text(p)), 'required-by before quote due date rejected');
  d.setDate(d.getDate() + 10); await inp[3].fill(d.toISOString().slice(0, 10));
  await H.fill(p, 'Weight — price (%)', '70');
  t.ok(/Weights total 110% — must be 100%/.test((await H.alerts(p)).join(' ')), 'weights must total 100');
  await H.fill(p, 'Weight — price (%)', '60');
  const chips = await p.$$('[role=dialog] .flex.flex-wrap.gap-1\\.5 button:not(.cursor-not-allowed)');
  await chips[0].click(); await H.sleep(100);
  t.ok(await H.disabled(p, 'Save & compose e-mail') === true, 'one vendor is not enough for multi-vendor mode');
  await chips[1].click(); await H.sleep(100);
  t.ok(await H.disabled(p, 'Save & compose e-mail') === false, 'valid RFQ can be saved');
  await p.keyboard.press('Escape'); await H.sleep(300);
  // quotation with FX on seeded RFQ-001
  await p.evaluate(() => { const r = [...document.querySelectorAll('main tr')].find(r => r.innerText.includes('TMT steel Fe500D')); r && r.click(); }); await H.sleep(600);
  await H.click(p, "Record quote on vendor's behalf", { dlg: false }).catch(async () => { await H.click(p, "Record quote on vendor's behalf"); });
  await H.pick(p, 'Currency', 'USD');
  const fx = await (await H.field(p, 'Exchange rate (₹ per USD)')).inputValue();
  t.ok(Number(fx) > 0, 'exchange rate field appears for foreign currency (' + fx + ')');
  await H.fill(p, 'Exchange rate (₹ per USD)', '0');
  t.ok(/Exchange rate must be greater than 0/.test((await H.alerts(p)).join(' ')), 'zero FX rejected');
  await H.fill(p, 'Exchange rate (₹ per USD)', '84');
  const rates = await p.$$('[role=dialog]:last-of-type table tbody input[type=number]');
  await rates[0].fill('700'); await rates[1].fill('150'); await H.sleep(100);
  t.ok(/discount must be 0–100%/.test(await H.text(p)), 'discount > 100 rejected');
  await rates[1].fill('0'); await rates[3].fill('690'); await H.sleep(100);
  t.ok(/≈ ₹/.test(await H.text(p)), 'INR equivalent shown for foreign-currency quote');
  await H.fill(p, 'Valid until', '2020-01-01');
  t.ok(/can't be in the past/.test((await H.alerts(p)).join(' ')), 'past validity rejected');
  const v = new Date(); v.setDate(v.getDate() + 30); await H.fill(p, 'Valid until', v.toISOString().slice(0, 10));
  await H.click(p, 'Save quotation'); await H.sleep(300);
  const st = await H.store(p);
  const q = st.rfqs.find(r => r.id === 'RFQ-001').quotes.find(x => x.currency === 'USD');
  t.ok(q && q.fx === 84 && q.rates[0] === 700, 'USD quote saved with FX 84');
  t.ok(errors.length === 0, 'no page errors: ' + errors.join('; '));
  await b.close(); return t.done();
};
